# Generated by Django 4.2.30 on 2026-04-15 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(editable=False, max_length=12, unique=True)),
                ('metodo_pago', models.CharField(choices=[('EFE', 'Efectivo'), ('TAR', 'Tarjeta'), ('TRA', 'Transferencia')], max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente_nombre', models.CharField(blank=True, max_length=150)),
                ('notas', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venta_items', to='productos.productovariante')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Item de venta',
                'verbose_name_plural': 'Items de venta',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha'], name='ventas_vent_fecha_8683f5_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['vendedor', 'fecha'], name='ventas_vent_vendedo_3e7b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['metodo_pago'], name='ventas_vent_metodo__7195f7_idx'),
        ),
    ]
