web: mkdir -p staticfiles && python manage.py migrate --noinput && python manage.py collectstatic --noinput --clear && gunicorn config.wsgi --bind 0.0.0.0:$PORT --workers 2 --timeout 120
worker: celery -A rosa_menta worker -l info
