# Generated by Django 4.2.30 on 2026-04-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_snapshot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agregado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item de carrito',
                'verbose_name_plural': 'Items de carrito',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=12, unique=True)),
                ('estado', models.CharField(choices=[('CRE', 'Creado'), ('PAG', 'Pagado'), ('ENV', 'Enviado'), ('ENT', 'Entregado'), ('CAN', 'Cancelado')], default='CRE', max_length=3)),
                ('metodo_pago', models.CharField(blank=True, choices=[('MP', 'MercadoPago'), ('EFE', 'Efectivo'), ('TRA', 'Transferencia')], max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedido_items', to='productos.productovariante')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'verbose_name_plural': 'Items de pedido',
            },
        ),
    ]
