# Generated by Django 4.2.30 on 2026-04-15 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('productos', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuarios.direccion'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.carrito'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carrito_items', to='productos.productovariante'),
        ),
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['estado', 'created_at'], name='pedidos_ped_estado_e73db6_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['usuario', 'estado'], name='pedidos_ped_usuario_cd8414_idx'),
        ),
        migrations.AddConstraint(
            model_name='carritoitem',
            constraint=models.UniqueConstraint(fields=('carrito', 'variante'), name='uniq_carrito_variante'),
        ),
        migrations.AddConstraint(
            model_name='carrito',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('usuario',), name='uniq_carrito_por_usuario'),
        ),
    ]
