# Generated by Django 4.2.30 on 2026-04-15 05:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('token_baja', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origen', models.CharField(choices=[('REG', 'Registro'), ('FORM', 'Formulario')], default='FORM', max_length=4)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suscriptor',
                'verbose_name_plural': 'Suscriptores',
                'ordering': ['-fecha_suscripcion'],
                'indexes': [models.Index(fields=['activo'], name='newsletter__activo_668658_idx'), models.Index(fields=['origen', 'activo'], name='newsletter__origen_31b80c_idx')],
            },
        ),
    ]
